version: "3.9"

services:

  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tbl
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    networks:
      - my_network

  mongoDB:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: tbl
    networks:
      - my_network


  persistence:
    image: persistence:0.1.0-SNAPSHOT
    ports:
      - "8081:8081"
    container_name: persistence-service
    depends_on:
      - db
      - mongoDB
    networks:
      - my_network
    working_dir: /fileio
    volumes:
        - ./:/fileio:xro

  core:
    image: core:0.1.0-SNAPSHOT
    ports:
      - "8082:8082"
    container_name: core-service
    depends_on:
      - persistence
    networks:
      - my_network

  ui:
    image: ui:0.1.0-SNAPSHOT
    stdin_open: true
    tty: true
    container_name: ui-service
    depends_on:
      - core
    networks:
      - my_network
    environment:
      DISPLAY: $DISPLAY

  ui2:
    image: ui:0.1.0-SNAPSHOT
    stdin_open: true
    tty: true
    container_name: ui-service2
    depends_on:
      - core
    networks:
      - my_network
    environment:
      DISPLAY: $DISPLAY

networks:
  my_network:
